### ISSUE TITLE
Items not added if bags are full

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-reward-played-time#5]
Currently if bags are full and your roll comes up the item is not added to bags or added to mail because bags are full.

**Comment by BarbzYHOOL** [comment]
I think if you add an item with .add and ur bags are full, u get it in the mail, so could check the .add command to reproduce this behaviour (let's hope it's a function)

**Comment by milestorme** [comment]
can confirm item not created using .add if bags are full

**Comment by BarbzYHOOL** [comment]
yes but it sends by mail, right?

**Comment by milestorme** [comment]
No it’s not sending with .add by mail if bags are full

**Comment by BarbzYHOOL** [comment]
ok so i said shit

**Comment by BarbzYHOOL** [comment]
When you equip an item lvl 80 and then you type .level -60, you are now under leveled. Then you log out and log back, your item should be mailed to you. Can check the code there to copy it

**Comment by wizzymore** [comment]
I think it would be simpler to check if ->AddItem returns false and if so to email the item to the player

**Comment by milestorme** [comment]
That’s a bad idea , then you would have to wait till raid was finished to check mail for upgrades , super bad idea wizzy I not trying to be mean , but look at it from a raiding perspective

**Comment by milestorme** [comment]
❤️❤️❤️❤️❤️❤️❤️❤️
